service: resume-screener
 
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false
 
provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1

functions:
  apiTest:
    handler: app.test
    events:
      - http:
          path: /test
          method: GET
  apiTestdb:
    handler: app.getCandidateList
    timeout: 30
    events:
      - http:
          path: /candidate-list
          method: GET
  apiJobOpening:
    handler: app.getJobOpeningList
    timeout: 30
    events:
      - http:
          path: /job-opening-list
          method: GET
  apiPostJob:
    handler: app.postJob
    timeout: 90
    events:
      - http:
          path: /post-job
          method: POST
  apiAppliedJob:
    handler: app.getAppliedJobs
    timeout: 30
    events:
      - http:
          path: /applied-jobs
          method: GET
  apiNonAppliedJob:
    handler: app.getNonAppliedJobs
    timeout: 30
    events:
      - http:
          path: /non-applied-jobs
          method: GET
  apiApplyJob:
    handler: app.applyJob
    timeout: 90
    events:
      - http:
          path: /apply-job
          method: POST
  apiApplicationsWithNoRelevancy:
    handler: app.getApplicationsWithNoRelevancy
    timeout: 90
    events:
      - http:
          path: /application-no-relevancy
          method: GET
  apiPostAverageRelevancy:
    handler: app.postAverageRelevancy
    timeout: 90
    events:
      - http:
          path: /post-average-relevancy
          method: POST
  apiGetJobById:
    handler: app.getJobById
    timeout: 90
    events:
      - http:
          path: /get-job-id
          method: GET

