service: resume-screener-v1
 
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false
 
provider:
  name: aws
  runtime: python3.10
  stage: dev
  region: us-east-1

functions:
  apiTest:
    handler: app.test
    events:
      - http:
          path: /test
          method: GET
          cors:
            origin: '*'  # Replace with your frontend domain or '*' for any domain
            headers:
              - Content-Type
            allowCredentials: false
  apiTestdb:
    handler: app.getCandidateList
    timeout: 30
    events:
      - http:
          path: /candidate-list
          method: GET
          cors:
            origin: '*'  # Replace with your frontend domain or '*' for any domain
            headers:
              - Content-Type
            allowCredentials: false
  apiJobOpening:
    handler: app.getJobOpeningList
    timeout: 30
    events:
      - http:
          path: /job-opening-list
          method: GET
          cors:
            origin: '*'  # Replace with your frontend domain or '*' for any domain
            headers:
              - Content-Type
            allowCredentials: false
  apiPostJob:
    handler: app.postJob
    timeout: 90
    events:
      - http:
          path: /post-job
          method: POST
          cors:
            origin: '*'  # Replace with your frontend domain or '*' for any domain
            headers:
              - Content-Type
            allowCredentials: false
  apiAppliedJob:
    handler: app.getAppliedJobs
    timeout: 30
    events:
      - http:
          path: /applied-jobs
          method: GET
          cors:
            origin: '*'  # Replace with your frontend domain or '*' for any domain
            headers:
              - Content-Type
            allowCredentials: false
  apiNonAppliedJob:
    handler: app.getNonAppliedJobs
    timeout: 30
    events:
      - http:
          path: /non-applied-jobs
          method: GET
          cors:
            origin: '*'  # Replace with your frontend domain or '*' for any domain
            headers:
              - Content-Type
            allowCredentials: false
  apiApplyJob:
    handler: app.applyJob
    timeout: 90
    events:
      - http:
          path: /apply-job
          method: POST
          cors:
            origin: '*'  # Replace with your frontend domain or '*' for any domain
            headers:
              - Content-Type
            allowCredentials: false
  apiApplicationsWithNoRelevancy:
    handler: app.getApplicationsWithNoRelevancy
    timeout: 90
    events:
      - http:
          path: /application-no-relevancy
          method: GET
          cors:
            origin: '*'  # Replace with your frontend domain or '*' for any domain
            headers:
              - Content-Type
            allowCredentials: false
  apiPostAverageRelevancy:
    handler: app.postAverageRelevancy
    timeout: 90
    events:
      - http:
          path: /post-average-relevancy
          method: POST
          cors:
            origin: '*'  # Replace with your frontend domain or '*' for any domain
            headers:
              - Content-Type
            allowCredentials: false
  apiGetJobById:
    handler: app.getJobById
    timeout: 90
    events:
      - http:
          path: /get-job-id
          method: GET
          cors:
            origin: '*'  # Replace with your frontend domain or '*' for any domain
            headers:
              - Content-Type
            allowCredentials: false

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
