"""initial migration

Revision ID: 022b22ec6cad
Revises: 
Create Date: 2023-10-01 22:20:32.344870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '022b22ec6cad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('user')
    with op.batch_alter_table('SequelizeMeta', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('SequelizeMeta')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('description')
        batch_op.drop_index('title')

    op.drop_table('jobs')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index('Address')
        batch_op.drop_index('City')
        batch_op.drop_index('FirstName')
        batch_op.drop_index('LastName')

    op.drop_table('persons')
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_index('address')
        batch_op.drop_index('firstName')
        batch_op.drop_index('lastName')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openingCount', sa.Integer(), nullable=False))
        batch_op.drop_index('description')
        batch_op.drop_index('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('title', ['title'], unique=False)
        batch_op.create_index('description', ['description'], unique=False)
        batch_op.drop_column('openingCount')

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_index('lastName', ['lastName'], unique=False)
        batch_op.create_index('firstName', ['firstName'], unique=False)
        batch_op.create_index('address', ['address'], unique=False)

    op.create_table('persons',
    sa.Column('PersonID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('LastName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('FirstName', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('City', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('PersonID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index('LastName', ['LastName'], unique=False)
        batch_op.create_index('FirstName', ['FirstName'], unique=False)
        batch_op.create_index('City', ['City'], unique=False)
        batch_op.create_index('Address', ['Address'], unique=False)

    op.create_table('jobs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('title', ['title'], unique=False)
        batch_op.create_index('description', ['description'], unique=False)

    op.create_table('SequelizeMeta',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=255), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('SequelizeMeta', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)

    # ### end Alembic commands ###
